# Generated by Django 5.1.4 on 2025-06-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_interaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=255, null=True, verbose_name="订单号"),
                ),
                (
                    "detail",
                    models.CharField(max_length=255, null=True, verbose_name="备注"),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="购买时的价格",
                    ),
                ),
                (
                    "trade_status",
                    models.SmallIntegerField(
                        choices=[(0, "待交易"), (1, "交易成功"), (2, "交易失败")],
                        null=True,
                        verbose_name="交易状态",
                    ),
                ),
                ("trade_time", models.DateTimeField(null=True, verbose_name="交易时间")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-create_time"],
            },
        ),
    ]
