# Generated by Django 5.2.2 on 2025-06-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_status',
            field=models.SmallIntegerField(choices=[(0, '待交易'), (1, '交易成功'), (2, '交易失败'), (3, '退款中')], null=True, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='交易时间'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='评论时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.comment', verbose_name='父级评论')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'ordering': ['-create_time'],
            },
        ),
    ]
