# Generated by Django 5.2.2 on 2025-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trade_status',
            field=models.SmallIntegerField(choices=[(0, '待交易'), (1, '交易成功'), (2, '交易失败'), (3, '退款中'), (4, '退款成功')], null=True, verbose_name='交易状态'),
        ),
    ]
